// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5gLftBpdN23INwG3et8web9Sra0n1Ka4',
    appId: '1:415822804267:web:0686e56283f5ba643ac16e',
    messagingSenderId: '415822804267',
    projectId: 'scada-hmi',
    authDomain: 'scada-hmi.firebaseapp.com',
    storageBucket: 'scada-hmi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz_-WBjCxFR2coEWu18bBarINNOJpS0oM',
    appId: '1:415822804267:android:851fd9c76b53ac9b3ac16e',
    messagingSenderId: '415822804267',
    projectId: 'scada-hmi',
    storageBucket: 'scada-hmi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTk6DzRLAlg0er8GWjQgv_4Hr9rdOyyZE',
    appId: '1:415822804267:ios:17175284715d5e073ac16e',
    messagingSenderId: '415822804267',
    projectId: 'scada-hmi',
    storageBucket: 'scada-hmi.firebasestorage.app',
    iosBundleId: 'com.example.scadaHmiFlooter',
  );
}
